version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.13.2
    working_directory: ~/gtdesignclub.com
    steps:
      - checkout
      # Check for cached dependencies
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      # Install dependencies
      - run:
          name: Installing dependencies... 
          command: npm install
      # Update cache
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths: 
            - node_modules
      # Build & cache project
      - run:
          name: Building site...
          command: npm run build
      - save_cache:
          paths:
            - .cache
            - public
          key: v1-gatsby-cache-{{ epoch }}
      - persist_to_workspace:
          root: ./
          paths:
            - "public"

  deploy:
    machine:
      image: ubuntu-2004:202111-02
    working_directory: ~/gtdesignclub.com
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "55:f0:8d:06:d6:64:93:de:fe:d4:2c:25:db:e7:87:98"
      - run: 
          name: Deploying over SSH...
          command: |
            scp -r ~/gtdesignclub.com/public/ -p $SSH_PORT $SSH_USER@$SSH_HOST:$SSH_DEPLOY_PATH

workflows:
  build-and-deploy:
    jobs:
        - build
        - deploy:
            requires:
              - build
            filters:
              branches: 
                only: main
