name: Build and Deploy
on: 
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with: 
          version: 8
          run_install: false
      - name: Get pnpm store dir
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Build app
        run: pnpm build
        env:
          CONTENTFUL_SPACE_ID: ${{secrets.CONTENFUL_SPACE_ID}}
          CONTENTFUL_TOKEN: ${{secrets.CONTENFUL_TOKEN}}
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env: 
          REPO: self
          BRANCH: deploy
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

