name: Build on Contentful Publish Event
on: 
  repository_dispatch:
    types: [publish-event]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16.x
      - name: Cache and Install Dependencies
        uses: bahmutov/npm-install@v1
      - name: Create .env
        run: |
          touch .env
          echo CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }} >> .env
          echo CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN }} >> .env
      - name: Build Project
        run: npm run build
